// Build a MINIMAL dist/ for the brand package.
//
// Why minimal: paragon build-scss emits a fully compiled Paragon theme
// (~180 KB). Layered on top of an MFE that already ships a complete Paragon
// theme via paragon-theme-variants-light.css, the two themes step on each
// other (utility classes, layout rules, tier scales) and break the UI.
//
// Instead, we run paragon build-tokens (which expands our overrides into
// every tier via Style Dictionary) and then extract ONLY the color
// declarations we own. The brand sheet ends up at a few KB and contains
// nothing but :root color custom property overrides — no layout side effects.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const tokensSrcDir = path.join(ROOT, 'paragon', 'tokens', 'src');
const generatedThemesDir = path.join(ROOT, 'paragon', 'build', 'themes');
const distDir = path.join(ROOT, 'dist');

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

// --- 1. Walk our source tokens to learn which categories we override ------
//
// For every leaf token we declare (e.g. color.primary.base), we want the
// generated CSS to include the FULL tier family (--pgn-color-primary-base,
// --pgn-color-primary-100 … 900). So we drop the trailing leaf segment when
// it's a tier marker (base / light / dark / a numeric step) and use the
// parent path as the prefix.

const TIER_LEAVES = new Set(['base', 'light', 'dark']);
const isTierLeaf = (segment) => TIER_LEAVES.has(segment) || /^\d+$/.test(segment);

const collectLeafPaths = (node, prefix = []) => {
  if (!node || typeof node !== 'object') return [];
  if ('$value' in node) return [prefix];
  const out = [];
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue; // skip $type/$description
    out.push(...collectLeafPaths(node[key], [...prefix, key]));
  }
  return out;
};

const walkJson = (dir) => {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkJson(p));
    else if (entry.name.endsWith('.json')) out.push(p);
  }
  return out;
};

const prefixes = new Set();
for (const file of walkJson(tokensSrcDir)) {
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  for (const leafPath of collectLeafPaths(json)) {
    const lastSegment = leafPath[leafPath.length - 1];
    const parentPath = isTierLeaf(lastSegment) ? leafPath.slice(0, -1) : leafPath;
    prefixes.add('--pgn-' + parentPath.join('-'));
  }
}

if (!prefixes.size) {
  console.error('build-dist: no token leaves found in paragon/tokens/src/');
  process.exit(1);
}

console.log('build-dist: extracting these prefixes from generated theme:');
for (const p of prefixes) console.log(`  ${p}-*`);

// --- 2. For each generated theme, pull matching declarations --------------

const matchesAnyPrefix = (varName) => {
  for (const p of prefixes) {
    if (varName === p || varName.startsWith(p + '-')) return true;
  }
  return false;
};

const extractDeclarations = (cssText) => {
  // CSS variables can have complex values (rgba, var(...), etc). We grab
  // each `--pgn-…: <value>;` declaration regardless of context.
  const re = /(--pgn-[a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
  const decls = [];
  let m;
  while ((m = re.exec(cssText)) !== null) {
    if (matchesAnyPrefix(m[1])) {
      decls.push(`  ${m[1]}: ${m[2].trim()};`);
    }
  }
  return decls;
};

const writeTheme = (themeName) => {
  const variablesCss = path.join(generatedThemesDir, themeName, 'variables.css');
  if (!fs.existsSync(variablesCss)) {
    console.warn(`build-dist: ${variablesCss} not found, skipping ${themeName}`);
    return false;
  }

  const decls = extractDeclarations(fs.readFileSync(variablesCss, 'utf8'));
  if (!decls.length) {
    console.warn(`build-dist: no declarations matched prefixes in ${themeName}`);
    return false;
  }

  const banner =
    `/* @openedx/brand-openedx — Axim brand overrides for ${themeName} theme.\n` +
    ` * Generated by scripts/build-dist.js. Edit paragon/tokens/src/ instead. */\n`;

  fs.writeFileSync(
    path.join(distDir, `${themeName}.css`),
    `${banner}:root {\n${decls.join('\n')}\n}\n`,
  );
  fs.writeFileSync(
    path.join(distDir, `${themeName}.min.css`),
    `${banner}:root{${decls.map(s => s.trim()).join('')}}`,
  );
  console.log(`build-dist: wrote ${themeName}.css with ${decls.length} declarations`);
  return true;
};

const themes = fs.existsSync(generatedThemesDir)
  ? fs.readdirSync(generatedThemesDir).filter(n =>
      fs.statSync(path.join(generatedThemesDir, n)).isDirectory())
  : [];

const built = themes.filter(writeTheme);

if (!built.length) {
  console.error('build-dist: no themes built. Did `paragon build-tokens` run?');
  process.exit(1);
}

// --- 3. Core stylesheet — intentionally near-empty ------------------------
//
// paragonUtils.js requires dist/core.{css,min.css} to exist for the brand
// override to be considered valid. We have no core-level overrides, so the
// file just needs to be present.

const coreNote =
  '/* @openedx/brand-openedx — core is intentionally empty; brand overrides live in light.css. */\n';
fs.writeFileSync(path.join(distDir, 'core.css'), coreNote);
fs.writeFileSync(path.join(distDir, 'core.min.css'), coreNote);

// --- 4. Manifest paragonUtils.js consumes ---------------------------------

const themeUrls = {
  themeUrls: {
    core: { paths: { default: './core.css', minified: './core.min.css' } },
    defaults: { light: 'light' },
    variants: Object.fromEntries(built.map(name => [
      name,
      { paths: { default: `./${name}.css`, minified: `./${name}.min.css` } },
    ])),
  },
};
fs.writeFileSync(
  path.join(distDir, 'theme-urls.json'),
  JSON.stringify(themeUrls, null, 2) + '\n',
);

console.log('build-dist: done.');
